theme: jekyll-theme-cayman
title: [Les Envois de Rome]
description: [La base de données concerne les travaux annuels des élèves de l’Académie de France à Rome, peintres et sculpteurs, pour la période 1804-1914.]
show_downloads: ["true"]
